name: Trigger auto deployment for testweb

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/testweb-AutoDeployTrigger-e3197c28-bdc5-44e9-a80f-026a8148eec5.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.TESTWEB_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TESTWEB_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TESTWEB_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: azurecont.azurecr.io
          registryUsername: ${{ secrets.TESTWEB_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TESTWEB_REGISTRY_PASSWORD }}
          containerAppName: testweb
          resourceGroup: obito_uchiha
          imageToBuild: azurecont.azurecr.io/testweb:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


